[pt-br]
  locale = 'pt-BR'
  direction = 'ltr'
  label = 'Português'
  title = 'EF-TECH'
  copyright = 'EF-TECH'
  weight = 1

  [pt-br.menu]
  [[pt-br.menu.main]]
    identifier = "home"
    name = "Inicio"
    pageRef = "/"
    weight = 10

  [[pt-br.menu.main]]
    identifier = "servicos"
    name = "Servicos"
    pageRef = "servicos"
    weight = 20

  [[pt-br.menu.main]]
    identifier = "produtos"
    name = "Produtos"
    pageRef = "produtos"
    weight = 25

  [[pt-br.menu.main]]
    identifier = "sobre"
    name = "Sobre"
    pageRef = "sobre"
    weight = 30

  [[pt-br.menu.main]]
    identifier = "blog"
    name = "Blog"
    pageRef = "blog"
    weight = 40

  [[pt-br.menu.main]]
    identifier = "contato"
    name = "Contato"
    pageRef = "contato"
    weight = 50

[en]
  locale = 'en'
  direction = 'ltr'
  label = 'English'
  title = 'EF-TECH'
  copyright = 'EF-TECH'
  weight = 2

  [en.menu]
  [[en.menu.main]]
    identifier = "home"
    name = "Home"
    pageRef = "/"
    weight = 10

  [[en.menu.main]]
    identifier = "services"
    name = "Services"
    pageRef = "servicos"
    weight = 20

  [[en.menu.main]]
    identifier = "products"
    name = "Products"
    pageRef = "produtos"
    weight = 25

  [[en.menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "sobre"
    weight = 30

  [[en.menu.main]]
    identifier = "blog"
    name = "Blog"
    pageRef = "blog"
    weight = 40

  [[en.menu.main]]
    identifier = "contact"
    name = "Contact"
    pageRef = "contato"
    weight = 50
