disabled = false
locale = "pt-br"
label = "Português"
weight = 1
title = "EF-TECH"

[params]
  displayName = "PT"
  isoCode = "pt-br"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.svg"
  description = "Soluções em cloud computing"
  copyright = "EF-TECH"

  [params.author]
    name = "EF-TECH"
    image = "img/logo.svg"
    imageQuality = 96
    headline = "Soluções em cloud computing"
    bio = "Transforme a performance e a segurança do seu ambiente com nossas soluções!"
    links = [
      { email = "mailto:contato@eftech.com.br" },
      { github = "https://github.com/eftechcombr" },
      { youtube = "https://youtube.com/@eftechcombr" }
    ]
