disabled = false
locale = "en"
label = "English"
weight = 2
title = "EF-TECH"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  description = "Cloud computing solutions"
  copyright = "EF-TECH"

  [params.author]
    name = "EF-TECH"
    image = "img/logo.png"
    imageQuality = 96
    headline = "Cloud computing solutions"
    bio = "Boost your infrastructure performance and security with our solutions!"
    links = [
      { email = "mailto:contato@eftech.com.br" },
      { github = "https://github.com/eftechcombr" },
      { youtube = "https://youtube.com/@eftechcombr" }
    ]
