contentTypeName = "blog"
subtitle = "Cloud computing solutions"
toc = true
showReadingTime = true
jsonLD = false
showAuthor = false

[author]
  name = "EF-TECH"
  email = "contato@eftech.com.br"

[search]
  summaryInclude = 180
  minMatchCharLength = 2
  threshold = 0.3

[header]
  logo = "img/logo.png"
  title = "EF-TECH"
  sticky = true

[footer]
  since = 2026
  poweredby = true

[taxonomies.icons]
  categories = "category-2"
  tags = "hash"

[giscus]
  enabled = false

[social_media]
  [[social_media.items]]
    enabled = true
    title = 'Email'
    icon = 'mail'
    link = 'mailto:contato@eftech.com.br'

  [[social_media.items]]
    enabled = true
    title = 'GitHub'
    icon = 'brand-github'
    link = 'https://github.com/eftechcombr'

  [[social_media.items]]
    enabled = true
    title = 'YouTube'
    icon = 'brand-youtube'
    link = 'https://youtube.com/@eftechcombr'

[pwa]
  enabled = false
